# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
name: ITF Examples CI
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  code:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./examples
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.8.0
      - name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.14.0
      - name: Run build
        run: |
          bazel build //...
      - name: Run test
        run: |
          bazel test --test_output=all //...
